# For local testing
version: "3.7"
services:
  database:
    image: mysql:latest
    volumes:
      - "test-volume:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
volumes:
  test-volume:
